version: '3.7'

services:
  db:
    image: mariadb:10.4
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d  # Mount the folder with SQL file
    networks:
      - app-network

  php:
    image: my-php-7.3-image:latest
    container_name: php73-apache
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
